server:
  port: 8082  
  
spring:
  cloud:
     gateway:
       routes:
        - id: first-service  
          uri: http://localhost:8083
          predicates:
          - Method=GET
        - id: second-service  
          uri: http://localhost:8084
          predicates:
          - Method=GET
          
